apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: python-db
    spec:
      containers:
      - name: python-app-update
        image: noortas/user-aggregation:3.0
        ports:
        - name: python-port
          containerPort: 5000
        env:
          - name: MYSQL_HOST
            value: database-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-python-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: sql-python-secrets
                key: database
